# Trabalho-Visualiza-o-e-Explora-o-de-Dados-2021
título : " Análise do PIB per capita dos municípios do estado de São Paulo "
saída :
  flexdashboard :: flex_dashboard :
    orientação : linha
    vertical_layout : preencher
    tema : jornal
    tempo de execução : brilhante    
---
`` `{r configuração, incluir = FALSO}
biblioteca ( flexdashboard )
biblioteca ( gapminder )
biblioteca ( dplyr )
biblioteca ( ggplot2 )
biblioteca ( plotly )
biblioteca ( readr )
biblioteca ( brilhante )
biblioteca ( folheto )
biblioteca ( RColorBrewer )
biblioteca ( rgdal )
biblioteca ( lubrificar )
biblioteca ( readxl )
shp  <-  rgdal :: readOGR ( " geojs-35-mun.json " )
dfsp  <- read_excel ( ' tabelamedia.xlsx ' )
dfshp  <- merge ( shp , dfsp , by.x  =  " id " , by.y  =  " Codigo_Municipio " , duplicateGeoms = TRUE )
dfshp  <-  dfshp [ dfshp $ Ano  ==  2002 ,]
`` `

Visualização no Mapa
======================================
---

###  Mapa de SP (Média do PIB per capita no período de 2002-2018)

`` `{r}
pal  <- colorBin ( " Reds " , domínio  =  dfshp $ MediaPIB_percapita , n = 5 )
cities_popup  <- paste0 ( " <strong> Município: </strong> " ,
                       dfshp $ Municipio ,
                        " <br> <strong> PIB: </strong> " ,
                       dfshp $ PIB ,
                        " <br> <strong> PIB per capita (média): </strong> " ,
                       dfshp $ MediaPIB_percapita ,
                        " <br> <strong> Indústria: </strong> " ,
                       dfshp $ Industria ,
                        " <br> <strong> Serviços: </strong> " ,
                       dfshp $ Servicos ,
                        " <br> <strong> Agropecuária: </strong> " ,
                       dfshp $ Agropecuaria ,
                        " <br> <strong> Impostos: </strong> " ,
                       dfshp $ Impostos )
folheto ( dfshp )% > %
  addProviderTiles ( " CartoDB.Positron " )% > %
  addPolygons ( fillColor  =  ~ pal ( dfshp $ MediaPIB_percapita ),
              fillOpacity  =  0,8 ,
              color  =  " # EB6864 " ,
              peso  =  1 ,
              popup  =  cities_popup )% > %
  addLegend ( " bottomright " , pal  =  pal , values  =  ~ MediaPIB_percapita ,
            title  =  " PIB per capita dos municípios de São Paulo (média do período 2002-2018) " ,
            opacidade  =  0,8 , layerId  =  " colorLegend " )  
`` `

Gráficos e Dados
======================================

Entradas {.sidebar}
----------------------------------
`` `{r} 
      selectInput ( " Municipio " , label  =  " Município: " ,
            escolhas = único ( dfsp $ Municipio ))
      sliderInput ( " Ano " , label  =  " Período: " ,
            min  =  2002 , max  =  2018 , valor  =  2018 , etapa  =  2 )
`` `

Linha {data-height = 350}
-------------------------------------------------- ---------------------

###  PIB

`` `{r}
renderPlotly ({
g = filter ( dfsp , Municipio  ==  input $ Municipio , Ano  < =  input $ Ano )% > %
    ggplot ( . , aes ( x = Ano , y = ( PIB / 1000000 ))) + geom_line ( color  =  " black " ) +
      theme_bw () + laboratórios ( y =  " PIB bilhões R $ " )
    ggplotly ( g )
})
`` `

###  PIB per capita

`` `{r}
renderPlotly ({
g = filter ( dfsp , Municipio  ==  input $ Municipio , Ano  < =  input $ Ano )% > %
    ggplot ( . , aes ( x = Ano , y = ( PIB_percapita / 1000 ))) + geom_line ( color  =  " # EB6864 " ) +
      theme_bw () + labs ( y =  " PIB per capita portugueses R $ " )
    ggplotly ( g )
})
`` `

Row {.tabset}
---

###  População

`` `{r}
renderPlotly ({
g = filter ( dfsp , Municipio  ==  input $ Municipio , Ano  < =  input $ Ano )% > %
    ggplot ( . , aes ( x = Ano , y = Populacao * 1000 )) + geom_col ( fill = " # EB6864 " , color  =  " # EB6864 " ) +
      theme_bw () + labs ( y =  " População " )
    ggplotly ( g )
})
`` `

###  Dados do município

`` `{r}
renderTable ({
  filtro ( dfsp , Municipio  ==  input $ Municipio )
})
`` `

(+)
===
`` `{r}
renderPlotly ({
    ggplot ( dfsp , aes ( x = Impostos , y = PIB_percapita / 1000 )) + geom_point ( col  =  " # EB6864 " ) +
      theme_bw () +
      scale_x_log10 () + labs ( title = " Gráfico de dispersão " , y =  " PIB per capita em R $ " , x =  " Impostos R $ (log10) " )
  })
`` `


